spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/studygroups
    username: ...
    password: ...

server:
  address: ...
  port: 1234

  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    enabled: true
    key-store-password: ...
